[project]
name = "birddata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.4.0",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
]
